### ISSUE TITLE
URL not working in HostMan

### ISSUE THREAD

**Issue by gnark** [crazy-max/HostsWindowsBlocker#1]
I guess it must have **.txt** at the end.
![hm_2016-02-08_22-54-18](https://cloud.githubusercontent.com/assets/8975930/12900544/42b9ad2a-ceb7-11e5-8590-5bfdd60239a6.png)

**Comment by crazy-max** [comment]
Hi,

It seems to be a Github issue (certificate?)
I keep you in touch.

**Comment by crazy-max** [comment]
You right it needs an extension

**Comment by crazy-max** [comment]
The file has been renamed `hosts.txt`

**Comment by crazy-max** [comment]
I have created a git hook to publish the hosts file to my personal website.
Add this url to HostsMan : [http://www.crazyws.fr/HostsWindowsBlocker.txt](http://www.crazyws.fr/HostsWindowsBlocker.txt)
